language: node_js
node_js:
  - node
  - lts/*
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
install:
  - yarn install --frozen-lockfile
script:
  - yarn run test:coverage
  - yarn run cy:start
  - yarn run cy:test
after_success:
  - yarn run test:coveralls
  - yarn run cy:start
  - yarn run cy:test
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache
